# Generated by Django 6.1 on 2026-08-25 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('compress', 'Compress'), ('reorder', 'Reorder')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('input_paths', models.JSONField(blank=True, default=list)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('output_path', models.CharField(blank=True, default='', max_length=512)),
                ('result_filename', models.CharField(blank=True, default='', max_length=255)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool', 'status'], name='pdf_pdfjob_tool_a08fb3_idx'), models.Index(fields=['expires_at'], name='pdf_pdfjob_expires_b6325b_idx')],
            },
        ),
    ]
