# Generated by Django 6.1 on 2026-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfjob',
            name='tool',
            field=models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('compress', 'Compress'), ('reorder', 'Reorder'), ('remove_pages', 'Remove pages')], max_length=16),
        ),
    ]
